# Generated by Django 4.0.2 on 2022-02-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='link',
        ),
    ]
