# Generated by Django 4.0.2 on 2022-02-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connected',
        ),
    ]
