# Generated by Django 4.0.2 on 2022-02-14 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_connection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
