version: '3.8'

services:
  web:
    build:
      context: ../../.
      dockerfile: Dockerfile.ci
      cache_from:
        - "${LATEST_WEB_IMAGE_TAG}"
    image: "${COMMIT_WEB_IMAGE_TAG}"
    command: gunicorn appcounter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
      - 8001
    env_file:
      - ../../.env
  nginx:
    build:
      context: ../nginx/.
      cache_from:
        - "${LATEST_NGINX_IMAGE_TAG}"
    image: "${COMMIT_NGINX_IMAGE_TAG}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
