version: '3.8'

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn appcounter.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
      - 8001
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: