version: "3.8"

services:
  redis:
    image: redis:latest
  nginx:
    build:
      context: ../../.
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: ../../.
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../.:/usr/src/app/
    ports:
      - "8000:8000"
    links:
      - redis
    env_file:
      - ../config/.env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=appcounter
      - POSTGRES_PASSWORD=appcounter
      - POSTGRES_DB=appcounter
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: