version: '3.8'

services:
  web:
    build:
      context: ../../.
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn appcounter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
      - 8001
    env_file:
      - ../config/.env.prod
    depends_on:
      - db
  nginx:
    build:
      context: ../nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../config/.env.prod.db
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  static_volume:
  postgres_data:
