version: '3.8'

services:
  web:
    build:
      context: ../../.
      dockerfile: Dockerfile.ci
      cache_from:
        - "${WEB_IMAGE}:latest"
    image: "${WEB_IMAGE}:${CI_COMMIT_SHA}"
    command: gunicorn appcounter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
      - 8001
    env_file:
      - ../../.env
  nginx:
    build:
      context: ../nginx/.
      cache_from:
        - "${NGINX_IMAGE}:latest"
    image: "${NGINX_IMAGE}:${CI_COMMIT_SHA}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
